services:
  app:
    build: .
    container_name: barbones_agent_app
    volumes:
      - .:/app
    # If you switch to chromadb.PersistentClient(path="/app/chroma_db_data") in tools.py,
    # you might want to add a volume for persistence:
    #  - chroma_data:/app/chroma_db_data

# volumes:
#   chroma_data:
